#!/bin/sh
#
# A wrapper script for Blender
#

# In case user's home directory doesn't contain ~/.blender, copy it
# from /usr/share/blender and the detected BLENDER_LIBDIR

if [ -x /usr/bin/blender-freeworld.bin ]; then
    blend="blender-freeworld"
else
    blend="blender"
fi

#Set the blender binary library directory
if [ -d ${BLENDER_LIBDIR}/plugins ]; then
  break
elif [ -d /usr/lib64/blender/plugins ]; then
  BLENDER_LIBDIR=/usr/lib64/blender
elif [ -d /usr/lib32/blender/plugins ]; then
  BLENDER_LIBDIR=/usr/lib32/blender
elif [ -d /usr/lib/blender/plugins ]; then
  BLENDER_LIBDIR=/usr/lib/blender
else
  echo "blender binary directory was not found or BLENDER_LIBDIR is wrong"
  exit 1
fi

if [ ! -d ~/.blender/2.56 ]; then
    mkdir -p ~/.blender/2.56
    ln -sf /usr/share/locale ~/.blender2.56/locale
 
    mkdir -p ~/.blender/plugins

    ln -sf /usr/share/blender/scripts ~/.blender/2.56

    if [ -d ${BLENDER_LIBDIR}/plugins ]; then
       ln -sf ${BLENDER_LIBDIR}/plugins/sequence ~/.blender/2.56/plugins/sequence
       ln -sf ${BLENDER_LIBDIR}/plugins/texture ~/.blender/2.56/plugins/texture
    fi
fi

#
# Fully update the plugins every time blender is launched.
#
for s in /usr/share/blender/scripts/* ; do
    s=`basename ${s}`
    mkdir -p ~/.blender/2.56/scripts/${s}
    for x in /usr/share/blender/scripts/${s}/* ; do
	ln -sf /usr/share/blender/scripts/${s}/${x} ~/.blender/scripts/2.56/${s}
    done
done

/usr/bin/${blend}.bin $@

